spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./testdb;DB_CLOSE_DELAY=-1;IFEXISTS=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      minimum-idle: 5                # Minimum number of idle connections in the pool
      maximum-pool-size: 20           # Maximum number of connections in the pool
      idle-timeout: 60000             # Time in milliseconds before an idle connection is removed
      max-lifetime: 1800000           # Maximum lifetime of a connection in the pool
      connection-timeout: 30000       # Maximum time to wait for a connection from the pool
      validation-timeout: 5000        # Time to wait for validation of a connection
      leak-detection-threshold: 600000 # Time in milliseconds to detect a connection leak
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
app:
  config:
    pancake:
      api-key: ${PANCAKE_API_KEY}
    shopify:
      access-token: ${SHOPIFY_ACCESS_TOKEN}
      subdomain: ${SHOPIFY_SUBDOMAIN}
      webhook-secret: ${SHOPIFY_WEBHOOK_SECRET}
    sapo:
      phone-number: ${SAPO_PHONE_NUMBER}
      password: ${SAPO_PASSWORD}
      client-id: ${SAPO_CLIENT_ID}
      shop-domain: ${SAPO_SHOP_DOMAIN}